DROP TABLE IF EXISTS inventories;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS reviews;

CREATE TABLE inventories (
	id SERIAL PRIMARY KEY,
	name VARCHAR(300) NOT NULL,
	description VARCHAR(600),
	price INTEGER,
	quantity INTEGER NOT NULL,
	image_url VARCHAR(600)
);

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(300),
	email VARCHAR(300) NOT NULL,
	password_digest VARCHAR(600)
);

CREATE TABLE carts (
	id SERIAL PRIMARY KEY,
	inventory_id INTEGER NOT NULL,
	quantity INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (inventory_id) REFERENCES inventories (id) ON DELETE RESTRICT,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE reviews (
	id SERIAL PRIMARY KEY,
	inventory_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	review VARCHAR(600),
	rating INTEGER,
	FOREIGN KEY (inventory_id) REFERENCES inventories (id) ON DELETE RESTRICT,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);